### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by SekiBetu** [JadaGates/ShadowsocksBio#14]

**Comment by iseki0** [comment]
？？？

**Comment by ghost** [comment]
？？？

**Comment by ghost** [comment]
？？？

**Comment by SekiBetu** [comment]
？？？

**Comment by Copay** [comment]
？？？

**Comment by DuckSoft** [comment]
？？？

**Comment by HMBSbige** [comment]
？？？

**Comment by devyujie** [comment]
???

**Comment by p4gefau1t** [comment]
？？？

**Comment by Sonic853** [comment]
¿

**Comment by ghost** [comment]
？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by j0hnnie** [comment]
？？？

**Comment by KeiKinn** [comment]
Hi, I know what you mean, but Vmess is not what I familiar with, and I also want to keep focus on SS only in this article now. I believe Vmess can survive from this crisis, pls keep positive, cause there is no such a system which do not have bugs, right? 

Thank you for you commit
