### ISSUE TITLE
墙其实成为了过滤的作用

### ISSUE THREAD

**Issue by esrrhs** [JadaGates/ShadowsocksBio#15]
有效的隔离了容易被外部环境洗脑的国内大量受教育程度不高的人，只需要看看微信里各种谣言转发就懂了。有能力翻墙的人，受蛊惑的概率小得多

**Comment by kouhe3** [comment]
有一说一,确实

昨天晚上
我爸在感叹：量子卫星千万不能落入美国手中
我凑近一看
是微信群的一条消息
内容大概是这样的
为什么美国怕中国？中国的量子卫星太厉害了！用量子技术拍摄的照片。清晰到可以看清路人的每一个动作。点击下方链接查看。
然后我看了一下。
那个链接。
就是一个全景地图而已。
http://www.bigpixel.cn/

**Comment by SekiBetu** [comment]
墙的风评随着时间的推移，说不定倒着来

**Comment by kouhe3** [comment]
>墙的风评随着时间的推移，说不定倒着来
@SekiBetu 

[环球时报:中国网络防火墙必将得到历史正面评价](http://news.china.com.cn/2016-04/11/content_38213968.htm)

**Comment by XuHaoIgeneral** [comment]
现在是我的账号被推特全ban了，就是我上去给华姐点了一个赞

**Comment by KeiKinn** [comment]
就我个人而言，我不是很支持墙作为过滤器的想法，虽然不可否认的是关于非法网站它是有用的，但是这种思维本身就是一种假性精英思维，隐隐约约有一种别人赶不上自己的感觉。

信息的闭塞以及来源单一化才会使人盲目，多元的信息渠道才是真正的兼听则明，至少有得选。

**Comment by esrrhs** [comment]
@JadaGates 真正的兼听则明，很难，等微信群里传播的那些“震惊”“刚刚”消停了，才行。对于那些用户来说，国外的"震惊"”刚刚“更能蛊惑人心，比如https://www.youtube.com/watch?v=-U9-awHL0l8

**Comment by SekiBetu** [comment]
> 就我个人而言，我不是很支持墙作为过滤器的想法，虽然不可否认的是关于非法网站它是有用的，但是这种思维本身就是一种假性精英思维，隐隐约约有一种别人赶不上自己的感觉。
> 
> 信息的闭塞以及来源单一化才会使人盲目，多元的信息渠道才是真正的兼听则明，至少有得选。

兼听则明是有前提的，不然国内那么多传销洗脑

**Comment by kouhe3** [comment]
的确是过滤的作用--------过滤掉朝.廷不喜欢的内容
