### ISSUE TITLE
如果把中国网民的十几年翻墙史写出来

### ISSUE THREAD

**Issue by kouhe3** [JadaGates/ShadowsocksBio#17]
一定会是一个可歌可泣的故事

**Comment by kouhe3** [comment]
? 怎么close 了
我以为会有人讨论怎么写来着

**Comment by KeiKinn** [comment]
Hello，其实我感觉你提出的想法特别好，只不过它需要更加专业的人去收集，整理各类信息，也许发起一个小小的投稿信息，并组织成册更能实现你的构想。

**Comment by kouhe3** [comment]
可以先创建一个wiki把梯子们记录一下，维基百科在梯子这一块的词条总是落后。

**Comment by kouhe3** [comment]
维基百科毕竟以严谨为主，更新不快也是有原因。
至于历史的话，我觉得主要围绕 反审查 写。不只是GFW,比如 [Signal 事件](https://github.com/net4people/bbs/issues/63)也可以写

**Comment by kouhe3** [comment]
https://zh.wikibooks.org/wiki/%E7%BF%BB%E5%A2%99%E7%AE%80%E5%8F%B2

那么开始吧

**Comment by kouhe3** [comment]
@TsingJyujing 您也来写吧

**Comment by TsingJyujing** [comment]
@kouhe3 我已经写了一篇，不过受限于个人知识水平不是很详细。不过我里面引用的几篇文章都很翔实。

https://blog.tsingjyujing.com/spam/gfw-history
