### ISSUE TITLE
安卓平台的软件大大介绍的怎么这么少😂

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [JadaGates/ShadowsocksBio#18]
phraos, clash, ss, ssr, ssrr, surfboard,kitsunebi, igniter, v2 rayng，大部分都支持分应用代理吧

**Comment by KeiKinn** [comment]
主要原因是我最初在写这篇文章的时候，当时可选择的余地很少，后来安卓也并非我的主力机，因此没有办法继续更新安卓部分的内容了。
