### ISSUE TITLE
这篇文章成文于什么时间？

### ISSUE THREAD

**Issue by TurnOffNOD** [JadaGates/ShadowsocksBio#24]
如题。
看文章内容没有clash这些后面的东西啊。

**Comment by muink** [comment]
ss停更都10年了 clash才56年前的东西
纠正下, ss 作者 clowwindy 是停更了, 但是项目截止目前依然在更新

**Comment by KeiKinn** [comment]
hello，这已经是一篇超过5年的旧文了，当时撰写的时候已经有clash了，但是 1. 对于clash的讨论与本文主题无关，2. 我个人对于clash的关注颇少，个人的知识水平不足。综合这两点想法，故并未包含clash在内。如果有人愿意记录clash的timeline，也是一件很好的事情。

**Comment by TurnOffNOD** [comment]
> hello，这已经是一篇超过5年的旧文了，当时撰写的时候已经有clash了，但是 1. 对于clash的讨论与本文主题无关，2. 我个人对于clash的关注颇少，个人的知识水平不足。综合这两点想法，故并未包含clash在内。如果有人愿意记录clash的timeline，也是一件很好的事情。

明白了，感谢回复。
