### ISSUE TITLE
推荐一个项目,快速搭建服务器

### ISSUE THREAD

**Issue by CaiJingLong** [JadaGates/ShadowsocksBio#3]
https://github.com/StreisandEffect/streisand

安装完成后包括WireGuard, OpenConnect, OpenSSH, OpenVPN, Shadowsocks, sslh, Stunnel, Tor bridge

**Comment by KeiKinn** [comment]
我将会对这个项目持续关注，考虑到现有文章的长度与主题，适当的时候可以以另外一篇文章介绍一下。

**Comment by cookyecat** [comment]
@JadaGates 你的文章写很好

**Comment by guyueshui** [comment]
mark一下，小传写的很好！

**Comment by VirtualboxWu** [comment]
写的真好

**Comment by nciefeiniu** [comment]
@JadaGates 写的就像看小说一样，👍
