### ISSUE TITLE
ss和ssr的故事在clash上重演了

### ISSUE THREAD

**Issue by snipersteve** [JadaGates/ShadowsocksBio#6]
Dreamacro写的clash为开源项目，但不支持ssr协议；因很多机场只提供ssr节点，广大小白用户希望支持ssr协议的呼声很高；lvguangfa在clash核心上加了ssr支持，闭源，向机场主收费，被人肉，被迫开源。
历史总是惊人相似。

**Comment by huqianshan** [comment]
Dreamacro貌似本人表示不赞成ssr,不愿花时间兼容ssr.但是支持别人提pr,最近好像有个分支已经完成基本功能，但暂时未合并进主分支。[add-ssr-support](https://github.com/Dreamacro/clash/pull/519)
同样的，clash项目的分支也是错综复杂，有clash-for-win,clashX,clash原版，以及各个机场主魔改的版本，比如支持ssr,支持中文汉化，增添皮肤。在接口上，也是另起炉灶，比如clash-for-win默认的是yml文件而不是原版的yaml格式，甚至演变出为两个yml配置文件，应用启动配置文件，以及用户分组配置

**Comment by esrrhs** [comment]
@snipersteve 哈哈 人性
