### ISSUE TITLE
其它平台也出现了不少新的客户端

### ISSUE THREAD

**Issue by Mosney** [JadaGates/ShadowsocksBio#7]
**Android：**
之前在hockyapp上公测的Surfboard，现在也已经在play商店发布1.0版本，唯一的劣势可能就是配置文件独树一帜。
Clash for Android也已经注册play商店超前体验，UI很漂亮，clash内核提供更广泛的兼容性。
Android还有一些我没用过的客户端，ClashA等。

**Windows：**
目前个人感觉Clash for Windows日臻完善。

**Others：**
另外目前x86机器做路由实现网关透明代理似乎也越来越流行，其中大部分是用的现有的ss+OpenWrt luci插件作为前端方案，还有少部分是用的clash+luci界面，据我所了解目前也有几个开发者在维护适用于OpenWrt的软件包或分支。

希望作者有余力可以添加一下相关信息和索引以指引同样水深火热的人。

> ref:
> Surfboard
> https://manual.getsurfboard.com/
> https://play.google.com/store/apps/details?id=com.getsurfboard
> 
> Clash及其各平台分支
> https://github.com/Dreamacro/clash
> 
> https://github.com/Kr328/ClashForAndroid
> https://play.google.com/store/apps/details?id=com.github.kr328.clash
> 
> https://github.com/Fndroid/clash_for_windows_pkg
> https://docs.cfw.lbyczf.com
> 
> https://github.com/frainzy1477/luci-app-clash
> https://github.com/vernesong/OpenClash
> https://github.com/coolsnowwolf/lede
> 
> http://firmware.koolshare.cn/
> https://github.com/SukkaW/Koolshare-Clash
>

**Comment by KeiKinn** [comment]
感谢

这段时间我会关注相关的项目。

**Comment by KeiKinn** [comment]
已经在文章做了简单的更新，感谢你的建议
